"""Add genre column to track table

Revision ID: 6ad18ef8dbaa
Revises: 
Create Date: 2025-05-16 23:02:57.489340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad18ef8dbaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('track_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_unique_constraint('track_id_key', ['id'])
        batch_op.drop_column('mood')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
