"""Add profile_image_url to user and last_updated to friend table

Revision ID: 7fd29bc5e124
Revises: 6ad18ef8dbaa
Create Date: 2025-05-21 08:17:34.219675

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '7fd29bc5e124'
down_revision = '6ad18ef8dbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime, nullable=True,
                                      server_default=sa.text('(CURRENT_TIMESTAMP)')))

    # Update existing friend records to have last_updated matching created_at
    op.execute('UPDATE friend SET last_updated = created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')
    # ### end Alembic commands ###